dist: bionic
language: cpp
compiler:
  - clang
  - gcc


before_install:
  - sudo apt-get install qtbase5-dev qttools5-dev qt5-default
script:
  - export QT_SELECT=qt5
  - qmake
  - make
  
 deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: release
  skip_cleanup: true
  
  
