version: 1.0.{build}
image: Visual Studio 2017

environment:
  matrix:
  - name: win32
    platform: amd64_x86
    qt: msvc2017_64
    
build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - set QTDIR=C:\Qt\5.12.4\msvc2017_64
  - set PATH=%PATH%;%QTDIR%\bin;
  - qmake
  - nmake
  
deploy:
  provider: GitHub
  auth_token: $(GITHUB_OAUTH_TOKEN)
  description: 'HelloCI Release'
  draft: false
  prerelease: false

